import React, { useEffect } from 'react';
import { motion } from 'motion/react';
import { Download, Share2, X } from 'lucide-react';

interface Props {
  imageUrl: string;
  onClose: () => void;
}

export function GeneratedImageOverlay({ imageUrl, onClose }: Props) {
  useEffect(() => {
    // Auto-dismiss after 60 seconds
    const timer = setTimeout(() => {
      onClose();
    }, 60000);
    return () => clearTimeout(timer);
  }, [onClose]);

  const handleDownload = async () => {
    try {
      // Fetch the image as a blob to trigger a clean download without navigating away
      const response = await fetch(imageUrl);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `generated-image-${Date.now()}.webp`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
    } catch (err) {
      console.error("Failed to download image", err);
      // Fallback: open in new tab if blob fetch fails (e.g., CORS)
      window.open(imageUrl, '_blank');
    }
  };

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Generated Image',
          url: imageUrl
        });
      } catch (err) {
        console.error("Error sharing", err);
      }
    }
  };

  return (
    <motion.div 
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      exit={{ opacity: 0, scale: 0.95 }}
      className="absolute inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm"
    >
      <div className="relative max-w-md w-full bg-zinc-900/80 border border-white/10 rounded-2xl overflow-hidden shadow-2xl backdrop-blur-md">
        <button 
          onClick={onClose}
          className="absolute top-3 right-3 p-2 bg-black/50 hover:bg-black/80 rounded-full text-white transition-colors z-10"
          aria-label="Close"
        >
          <X size={20} />
        </button>
        
        <img 
          src={imageUrl} 
          alt="Generated by AI" 
          className="w-full h-auto object-cover aspect-square"
        />
        
        <div className="p-4 flex gap-3 justify-center bg-zinc-900/90">
          <button 
            onClick={handleDownload}
            className="flex-1 flex items-center justify-center gap-2 py-2.5 bg-white/10 hover:bg-white/20 text-white rounded-xl transition-colors font-medium"
          >
            <Download size={18} /> Download
          </button>
          {typeof navigator.share === 'function' && (
            <button 
              onClick={handleShare}
              className="flex-1 flex items-center justify-center gap-2 py-2.5 bg-white/10 hover:bg-white/20 text-white rounded-xl transition-colors font-medium"
            >
              <Share2 size={18} /> Share
            </button>
          )}
        </div>
      </div>
    </motion.div>
  );
}
